site_name: PTE-XDF
site_description: "Load XDF files in MNE."
repo_url: "https://github.com/richardkoehler/pte-xdf"
repo_name: "richardkoehler/pte-xdf"
# site_url: "https://pawamoy.github.io/duty"
# site_dir: "site"

theme:
  name: "material"

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          import:
            - https://docs.python.org/3/objects.inv
          options:
            docstring_style: numpy
  - search

nav:
  - Home: index.md
  - 1. Installation: installation.md
  - 2. Quickstart Guide: quickstart-guide.md
  - 3. API Reference: api-reference.md
  - 4. How To Contribute: contribute.md
  - Changelog: CHANGELOG.md
  - License: license.md