name: Example workflow for Codecov
on: [push]
jobs:
  codecov:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: 3.10 Linux, python: '3.10', os: ubuntu-latest}
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python }}
    - name: Generate coverage report
      run: |
        pip install -e .[dev]
        pytest --cov=./ --cov-report=xml:./coverage/reports/coverage.xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        # env_vars: OS,PYTHON
        fail_ci_if_error: true
        # files: ./coverage/reports/coverage.xml
        name: codecov-umbrella
        # path_to_write_report: ./coverage/codecov_report.txt
        # verbose: true